# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # configuring forwarded ports
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  # docker config section
  config.vm.provider "docker" do |d|
    d.image = "elasticsearch"
    d.ports = ['9200:9200']
  end
end
